name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Add Playwright Package
      working-directory: tests
      run: dotnet add package Microsoft.Playwright

    - name: Restore dependencies
      working-directory: tests
      run: dotnet restore

    - name: Build
      working-directory: tests
      run: dotnet build --configuration Release --no-restore

    - name: Install Playwright Browsers (Only Chromium)
      working-directory: tests
      run: |
        dotnet build
        pwsh bin/Debug/net8.0/playwright.ps1 install chromium

    - name: Ensure directories exist
      run: |
        mkdir -p tests/bin/Debug/net8.0/playwright-traces
        mkdir -p tests/bin/Debug/net8.0/videos

    - name: Run Playwright Tests (Headless with Tracing)
      working-directory: tests
      run: PLAYWRIGHT_HEADLESS=1 dotnet test --logger "trx;LogFileName=TestResults.trx" --trace on

    - name: Upload Test Results
      if: always() # Upload even if tests pass or fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/TestResults/TestResults.trx
        retention-days: 1

    - name: Upload Playwright Traces
      if: always() # Upload even if tests pass or fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: tests/bin/Debug/net8.0/playwright-traces/*.zip
        retention-days: 1

    - name: Upload Playwright Videos
      if: always() # Upload even if tests pass or fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-videos
        path: tests/bin/Debug/net8.0/videos/*.webm
        retention-days: 1
